INPUT_SIZE:
- 112
- 112
backbone:
- - 1
  - DWConv
  - - 21
    - 3
    - 1
    - null
    - ReLU
- - 1
  - Conv
  - - 32
    - 5
    - 2
    - null
    - 1
    - ReLU
- - 2
  - MBConv
  - - 3
    - 80
    - 1
    - 5
- - 1
  - AvgPool
  - - 3
    - 2
    - 1
- - 5
  - Conv
  - - 16
    - 1
    - 1
    - null
    - 1
    - ReLU
- - 1
  - InvertedResidualv2
  - - 96
    - 4
    - 2
- - 4
  - ECAInvertedResidualv3
  - - 3
    - 2.5
    - 40
    - 5
    - 0
    - 1
- - 1
  - BottleneckAttn
  - - 2048
    - 1
    - 1
    - 4
- - 1
  - Conv
  - - 512
    - 1
    - 1
- - 1
  - GlobalAvgPool
  - []
- - 1
  - Flatten
  - []
- - 1
  - Linear
  - - 6
depth_multiple: 0.5
input_channel: 3
width_multiple: 0.75
