INPUT_SIZE:
- 112
- 112
backbone:
- - 1
  - DWConv
  - - 24
    - 3
    - 1
    - null
    - Hardswish
- - 1
  - DWConv
  - - 48
    - 3
    - 2
    - null
    - Hardswish
- - 1
  - InvertedResidualv3
  - - 5
    - 2.6
    - 96
    - 0
    - 0
    - 2
- - 1
  - DWConv
  - - 48
    - 3
    - 2
    - null
    - Hardswish
- - 2
  - Conv
  - - 16
    - 3
    - 1
    - null
    - 1
    - ReLU
- - 1
  - BottleneckAttn
  - - 2048
    - 14
    - 1
    - 4
- - 5
  - BottleneckAttn
  - - 1024
    - 14
    - 1
    - 4
- - 5
  - BottleneckAttn
  - - 1024
    - 14
    - 1
    - 4
- - 1
  - Conv
  - - 512
    - 1
    - 1
- - 1
  - Conv
  - - 512
    - 1
    - 1
- - 1
  - GlobalAvgPool
  - []
- - 1
  - FixedConv
  - - 6
    - 1
    - 1
    - null
    - 1
    - null
depth_multiple: 0.25
input_channel: 3
width_multiple: 0.75
