INPUT_SIZE:
- 112
- 112
backbone:
- - 1
  - Conv
  - - 16
    - 3
    - 1
    - null
    - 1
    - ReLU
- - 1
  - InvertedResidualv3
  - - 3
    - 3.1
    - 64
    - 1
    - 0
    - 2
- - 1
  - InvertedResidualv2
  - - 112
    - 4
    - 2
- - 1
  - ECAInvertedResidualv2
  - - 16
    - 3
    - 1
    - 5
- - 1
  - MaxPool
  - - 3
    - 2
    - 1
- - 4
  - Fire
  - - 16
    - 256
    - 256
- - 6
  - InvertedResidualv3
  - - 3
    - 2.4
    - 208
    - 0
    - 0
    - 1
- - 8
  - MBConv
  - - 3
    - 240
    - 1
    - 3
- - 1
  - Conv
  - - 512
    - 1
    - 1
- - 1
  - GlobalAvgPool
  - []
- - 1
  - Flatten
  - []
- - 1
  - Linear
  - - 6
depth_multiple: 0.5
input_channel: 3
width_multiple: 1.0
