INPUT_SIZE:
- 32
- 32
backbone:
- - 1
  - DWConv
  - - 15
    - 3
    - 1
    - null
    - ReLU
- - 1
  - InvertedResidualv2
  - - 48
    - 4
    - 2
- - 1
  - InvertedResidualv3
  - - 5
    - 1.6
    - 96
    - 1
    - 1
    - 1
- - 2
  - InvertedResidualv3
  - - 5
    - 2.9
    - 160
    - 1
    - 1
    - 1
- - 1
  - MaxPool
  - - 3
    - 2
    - 1
- - 3
  - DWConv
  - - 16
    - 5
    - 1
    - null
    - ReLU
- - 1
  - MaxPool
  - - 3
    - 2
    - 1
- - 1
  - DWConv
  - - 64
    - 3
    - 1
    - null
    - ReLU
- - 5
  - InvertedResidualv3
  - - 3
    - 4.0
    - 208
    - 0
    - 0
    - 1
- - 1
  - Conv
  - - 1024
    - 1
    - 1
- - 1
  - GlobalAvgPool
  - []
- - 1
  - Flatten
  - []
- - 1
  - Linear
  - - 6
depth_multiple: 0.75
input_channel: 3
width_multiple: 0.5
